[features]
seeds = false
[programs.localnet]
solancer = "FWPedSThzPVNU7QUjgVnJSDJFpd6P64KExFKxXUT5DtC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/trannguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
